name: release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
permissions:
  contents: write
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Typst
        uses: yusancky/setup-typst@v2
        id: setup-typst
        with:
          version: 'v0.9.0'

      - name: Clone BoneDocument/BoneDocument
        uses: GuillaumeFalourd/clone-github-repo-action@v2.2
        with:
          depth: 1
          branch: 'main'
          owner: 'BoneDocument'
          repository: 'BoneDocument'

      - name: Clone BoneDocument/fonts
        uses: GuillaumeFalourd/clone-github-repo-action@v2.2
        with:
          depth: 1
          branch: 'main'
          owner: 'BoneDocument'
          repository: 'fonts'

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Install Typst Packages
        run: |
          mkdir -p ~/.local/share/typst/packages/local/bone-document/
          ln -s $(pwd)/BoneDocument ~/.local/share/typst/packages/local/bone-document/0.1.0

      - name: Compile typst files
        run: |
          typst compile --font-path="./fonts/" reports/main.typ

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: reports/main.pdf
